### ISSUE TITLE
App has been crashed after select an image from gallery

### ISSUE THREAD

**Issue by ParryPatel021** [adigunhammedolalekan/easyphotoupload#1]
When I am going to select an image from a gallery, the app has been crashed immediately.

**Comment by adxgun** [comment]
Hi, can you provide the error logs?

**Comment by Ideasandkanishk** [comment]
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.graphics.Bitmap.compress(android.graphics.Bitmap$CompressFormat, int, java.io.OutputStream)' on a null object reference
        at com.beem24.projects.easyphotoupload.util.Util.getCompressed(Util.java:63)
        at com.beem24.projects.easyphotoupload.core.ImageCompressTask.run(ImageCompressTask.java:47)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:818)

**Comment by ParryPatel021** [comment]
Accidentally closed due to some popups
